package de.visterion.agora.research.fundamentals;

public enum FundamentalConcept {
    TOTAL_ASSETS, CURRENT_ASSETS, CURRENT_LIABILITIES, LONG_TERM_DEBT, TOTAL_LIABILITIES,
    RETAINED_EARNINGS, EBIT, REVENUE, GROSS_PROFIT, NET_INCOME, OPERATING_CASH_FLOW, SHARES_OUTSTANDING
}
